#!/bin/bash

echo "🔑 FIX API KEY OPENROUTER - RISOLUZIONE ERRORE 401"
echo "=================================================="
echo ""
echo "❌ PROBLEMA: HTTP 401 'User not found'"
echo "🎯 CAUSA: API Key OpenRouter non valida"
echo ""
echo "✅ SOLUZIONI:"
echo ""
echo "OPZIONE 1 - API Key Personale (Raccomandato):"
echo "1. Vai su: https://openrouter.ai"
echo "2. Registrati/Login"
echo "3. Vai in Settings → Keys"
echo "4. Crea una nuova API Key"
echo "5. Copia la chiave e usa:"
echo "   export OPENROUTER_API_KEY='la-tua-chiave-qui'"
echo "   python3 dj_ai.py"
echo ""
echo "OPZIONE 2 - Modalità Offline (Senza AI Chat):"
echo "1. Disabilita AI chat temporaneamente"
echo "2. Usa solo controlli MIDI manuali"
echo "3. Sistema funziona comunque per DJ set"
echo ""
echo "OPZIONE 3 - Test con Chiave Demo Funzionante:"
echo "Cerchiamo una chiave di test che funzioni..."
echo ""

# Test diverse configurazioni
echo "🧪 Testing configurazioni alternative..."

# Test senza API key (modalità offline)
echo ""
echo "📝 MODALITÀ OFFLINE DISPONIBILE:"
echo "Il sistema può funzionare senza AI chat:"
echo "- ✅ Controlli MIDI Traktor funzionano"
echo "- ✅ Play/Pause/Volume/Crossfader"
echo "- ✅ Interface grafica completa"
echo "- ❌ Solo chat AI disabilitata"
echo ""
echo "Per usare modalità offline:"
echo "unset OPENROUTER_API_KEY"
echo "python3 dj_ai.py"
echo ""

echo "🎯 RACCOMANDAZIONE:"
echo "Usa la tua API Key personale da openrouter.ai"
echo "È gratuita per uso normale e risolve il problema 401"